export {default as SingleCourse_Buttons_Enroll} from "./single-course/buttons/enroll.js"
export {default as SingleCourse_Buttons_Purchase} from "./single-course/buttons/purchase.js"
export {default as SingleCourse_Buttons_Submit} from "./single-course/buttons/submit.js"
export {default as SingleCourse_ContentLanding} from "./single-course/content-landing.js"
export {default as SingleCourse_ContentLearning} from "./single-course/content-learning.js"
export {default as SingleCourse_Content} from "./single-course/content.js"
export {default as SingleCourse_CourseTabs} from "./single-course/course-tabs.js"
export {default as SingleCourse_Lesson_ButtonSubmit} from "./single-course/lesson/button-submit.js"
export {default as SingleCourse_Lesson_Content} from "./single-course/lesson/content.js"
export {default as SingleCourse_Lesson_Index} from "./single-course/lesson/index.js"
export {default as SingleCourse_Progress} from "./single-course/progress.js"
export {default as SingleCourse_Quiz_Buttons_Start} from "./single-course/quiz/buttons/start.js"
export {default as SingleCourse_Quiz_Content} from "./single-course/quiz/content.js"
export {default as SingleCourse_Quiz_Index} from "./single-course/quiz/index.js"
export {default as SingleCourse_Section_Index} from "./single-course/section/index.js"
export {default as SingleCourse_Tabs_Index} from "./single-course/tabs/index.js"
export {default as SingleCourse_Tabs_TabCurriculum} from "./single-course/tabs/tab-curriculum.js"
export {default as SingleCourse_Tabs_TabInstructor} from "./single-course/tabs/tab-instructor.js"
export {default as SingleCourse_Tabs_TabOverview} from "./single-course/tabs/tab-overview.js"
// For watching files change
// export const rand = function(){ return 'Thu Aug 29 2019 13:36:07 GMT+0700 (Indochina Time)'}